### ISSUE TITLE
Portis and IPFS issue?

### ISSUE THREAD

**Issue by drbh** [portis-project/web-sdk#13]
If I import IPFS and Portis into my Node app it breaks...

```javascript
import Portis from "@portis/web3";
import Web3 from "web3";
import IPFS from "ipfs";
```

I get the following error
```bash
node_modules/libp2p-switch/src/connection/manager.js: Property name expected type of string but got null
```

This fails on compilation even if I never init IPFS

however 

```javascript
import Portis from "@portis/web3";
import Web3 from "web3";
```
works no problems.

Looks like some overlap in the libp2p-switch used in the portis wallet. Any idea how to fix this issue?

**Comment by radotzki** [comment]
@drbh what version of `@portis/web3`, `web3` and `ipfs` do you use?

**Comment by drbh** [comment]
```
"dependencies": {
	"@portis/web3": "2.0.0",
	"eth-ecies": "^1.0.3",
	"ipfs": "^0.35.0",
	"js-sha3": "^0.8.0",
	"secp256k1": "^3.7.0",
	"web3": "1.0.0-beta.41"
}
```

**Comment by radotzki** [comment]
@drbh I didn't manage to reproduce the issue with the dependencies you listed and this code:
```javascript
import Portis from "@portis/web3";
import Web3 from "web3";
import IPFS from "ipfs";

console.log('Portis', Portis);
console.log('Web3', Web3);
console.log('IPFS', IPFS);
```

Can you share a code snippet?

**Comment by drbh** [comment]
hmm, must be related to `parcel-bundler`?

Heres the code: https://github.com/drbh/portis-wallet-ext

```
npm install
npm start
```

thanks!

**Comment by radotzki** [comment]
It looks like an issue with Parcel and IPFS, this also fails:
```javascript
import IPFS from "ipfs";
console.log("IPFS", IPFS);
```

I suggest using `webpack` instead of `parcel`, see my PR:
https://github.com/drbh/portis-wallet-ext/pull/1

Let me if it works for you :)

**Comment by drbh** [comment]
awesome! works perfectly (had to add `acorn` as a dep) but after that everything is working as expected. Thanks man!
