### ISSUE TITLE
Lot of calls to provider

### ISSUE THREAD

**Issue by PierreJeanjacquot** [portis-project/web-sdk#23]
Hi,
I'm integrating Portis as a alternative to our traditional MetaMask web3 provider in a dapp UI.
Your really did a great job for UX, Portis really take a new look on web3 and will help to kickstart the dapps adoption.
I'm just surprised to see high frequency polling on infura nodes, do you have any plan for improvement?

**Comment by radotzki** [comment]
Hi @PierreJeanjacquot :)

Thanks for the feedback!

We use a library to fetch the latest block ([https://github.com/MetaMask/eth-block-tracker](eth-block-tracker)). That library polling the nodes every 5 seconds, and most of the requests you see are from this library. 

Does this cause any performance issues for you?

**Comment by usman-maavan** [comment]
@radotzki Can't we have a config/option that will define the pooling interval? Or maybe a method to stop the pooling if possible
Thanks,
