### ISSUE TITLE
node cannot compile the coding with ts or js file.

### ISSUE THREAD

**Issue by RYANCOAL9999** [portis-project/web-sdk#3]
the location is undefined on node_modules/@portis/web3/lib/utils/secureOrigin.js.

<img width="654" alt="screen shot 2019-02-22 at 2 31 17 pm" src="https://user-images.githubusercontent.com/16011027/53224963-71ed5000-36b1-11e9-8930-307462d45e8f.png">

the ts compile or using js is using same coding with node processing.
 
let Portis = require("@portis/web3");
let WEB3 = require("web3");
const INFURA_API_KEY = '1a0685b5-19a5-5q76-ax88-3612160fe138';(this api key is provided the your website with registered account for email)
var portis = new Portis.default(INFURA_API_KEY, 'mainnet');
var web3 = new WEB3(portis.provider);
web3.eth.getAccounts((error, accounts) => {
     console.log(accounts);
});

But It is no problem on website testing with two source coding link.
"https://cdn.jsdelivr.net/npm/web3@0.19.0/dist/web3.min.js"
"https://cdn.jsdelivr.net/npm/@portis/web3/umd/index.min.js"

I have using the coding with only on website with https://jsfiddle.net.
const portis = new Portis('1a0685b5-19a5-5q76-ax88-3612160fe138', 'mainnet');
const web3 = new Web3(portis.provider);

web3.eth.getAccounts((error, accounts) => {
        console.log(accounts);
});

Please help and fix this issues, thank you.

**Comment by radotzki** [comment]
Hi 👋 
Can you please share your tsconfig file?

**Comment by RYANCOAL9999** [comment]
my tsconfig.js is here :
{
  "compilerOptions": {
      "module": "commonjs",
      "target": "es2018",
      "noImplicitAny": true,
      "outDir": "./dist",
      "sourceMap": true
  },
  "files" : [
    "main.ts"
  ]
}

Please help and fix this issues, thank you.

**Comment by radotzki** [comment]
And do you use Webpack or another bundling tool?

**Comment by RYANCOAL9999** [comment]
No, I just compile the ts file with tsc(included tsconfig.js), after using vscode to run and debug main.js.

**Comment by radotzki** [comment]
You can not run Portis in a non-browser environment (like vscode-debug/nodejs). Try to run this code inside a browser, and let me know if that works.

**Comment by steflight** [comment]
I have the same issues , since yesterday i'm trying to handle it , but no success . 
![image](https://user-images.githubusercontent.com/5181443/61358939-b0abbe80-a87b-11e9-82b8-32dea401e1a2.png)
The error is : ReferenceError: location is not defined 
I just compile the ts file with tsc (to start my code in the browser) . 
I use nodeJs , express with typescript .
Please help and fix this issues, thank you.

**Comment by radotzki** [comment]
Hi @steflight 👋

Portis was designed to work only inside a browser.
You can not use Portis inside a NodeJS app.
