### ISSUE TITLE
Dependency fetched from github

### ISSUE THREAD

**Issue by PierreJeanjacquot** [portis-project/web-sdk#43]
Hi,

One of the dependencies used by `@portis/web3` is fetched from github
In `@portis/web3-provider-engine` :
```json
{
  "name": "@portis/web3-provider-engine",
  "version": "1.0.10",
  ...
  "author": "",
  "license": "MIT",
  "dependencies": {
    ...
    "eth-json-rpc-middleware": "github:radotzki/eth-json-rpc-middleware#patch-1",
    ...
  },
  ...
}
```

Is it possible to publish a proper release of `eth-json-rpc-middleware` on npm and fix the dependencies to avoid fetching package from github?

**Comment by radotzki** [comment]
Fixed.
