### ISSUE TITLE
portis.isLoggedIn() always returns false

### ISSUE THREAD

**Issue by j10sanders** [portis-project/web-sdk#49]
Posting an issue from https://portis.hellonext.co/features/detecting-user-login because it was closed.

I'm always getting `null, false` for `portis.isLoggedIn().then(({ error, result }) => { console.log(error, result); });`

Even when the user is logged in.

**Comment by radotzki** [comment]
Thanks for the feedback! 🙏
We fixed this issue, you can see an example here:
https://codesandbox.io/s/automatic-login-02kql

Please let me know if it works for you and I'll close this issue :)

**Comment by j10sanders** [comment]
wonderful, it works.  Thank you.

**Comment by j10sanders** [comment]
@radotzki - hey, I just noticed that your fix worked for if the user is logged in, but now, if the user is not logged in, the promise never resolves.  So there is never: `result: false`

**Comment by j10sanders** [comment]
For context, I want to show a loading screen while I check if the user is logged in.  And then once I find out they aren't logged in (and the portis modal pops up), I want to tell the user to sign in/register.
